<a href="https://colab.research.google.com/github/omarfarukcse/Machine-learning/blob/Pandas/Pandas_Practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

print(f"Pandas Version check : {pd.__version__}")

Pandas Version check : 2.2.2

In [ ]:
#Creating A Series
cars = pd.Series(["BMW","Toyota","Honda","BYD","Mercedece"])
print(cars)

0          BMW
1       Toyota
2        Honda
3          BYD
4    Mercedece
dtype: object

In [ ]:
colors = pd.Series(["Black","White","Red","Blue","Merun"])
colors

0    Black
1    White
2      Red
3     Blue
4    Merun
dtype: object

In [ ]:
model = pd.Series([2000,2001,2002,2003,2004])
model

0    2000
1    2001
2    2002
3    2003
4    2004
dtype: int64

In [ ]:
car_data = pd.DataFrame({"Car_type":cars,
                         "Color":colors,
                         "Model":model})
car_data

    Car_type  Color  Model
0        BMW  Black   2000
1     Toyota  White   2001
2      Honda    Red   2002
3        BYD   Blue   2003
4  Mercedece  Merun   2004

In [ ]:
from google.colab import sheets
sheet = sheets.InteractiveSheet(df=car_data)

https://docs.google.com/spreadsheets/d/1yUNaK6sSz5efQDwsxQEdI8BDnp6FUSecj1Ua5DdA28o/edit#gid=0

### Dictionary to Series and DataFrame

In [3]:
#Making Dictionary
data ={
    'name':["Omar","Efaz","Kobir","Jobair"],
    'age' : [24,23,24,25],
    'city':["Rangpur","Bogura","Tangail","Barishal"]
}
data

{'name': ['Omar', 'Efaz', 'Kobir', 'Jobair'],
 'age': [24, 23, 24, 25],
 'city': ['Rangpur', 'Bogura', 'Tangail', 'Barishal']}

In [20]:
#Making Series
print(f"This is a Name series :\n{pd.Series(data['name'], name='Name')}")
print(f"This is a Age series :\n{pd.Series(data['age'], name='Age')}")
print(f"This is a City series :\n{pd.Series(data['city'], name='City')}")

# naming the series also coded. name = 'Name' -> this is that
# also we can make variables s_name,s_age,s_city than print

This is a Name series :
0      Omar
1      Efaz
2     Kobir
3    Jobair
Name: Name, dtype: object
This is a Age series :
0    24
1    23
2    24
3    25
Name: Age, dtype: int64
This is a City series :
0     Rangpur
1      Bogura
2     Tangail
3    Barishal
Name: City, dtype: object

In [17]:
#Making DataFrame
pd.DataFrame(data)

     name  age      city
0    Omar   24   Rangpur
1    Efaz   23    Bogura
2   Kobir   24   Tangail
3  Jobair   25  Barishal

In [21]:
#Another way
pd.DataFrame.from_dict(data)

     name  age      city
0    Omar   24   Rangpur
1    Efaz   23    Bogura
2   Kobir   24   Tangail
3  Jobair   25  Barishal

#Set to Series and DataFrame

In [23]:
#Set create with {} -> this

s ={1,2,3,4,5,6,7,8,9}
s

{1, 2, 3, 4, 5, 6, 7, 8, 9}

In [24]:
type(s)

set

In [32]:
#we must have to convert set to list or tuple.
#Otherwise It will not work
print(f"Convert in List then Series : \n{pd.Series(list(s))}")
print(f"Convert in Tuple then Series : \n{pd.Series(tuple(s))}")

Convert in List then Series :
0    1
1    2
2    3
3    4
4    5
5    6
6    7
7    8
8    9
dtype: int64
Convert in Tuple then Series :
0    1
1    2
2    3
3    4
4    5
5    6
6    7
7    8
8    9
dtype: int64

In [38]:
#Set to DataFrame ... Easy Task heheheheh
pd.DataFrame(s, columns=["set_val"])

   set_val
0        1
1        2
2        3
3        4
4        5
5        6
6        7
7        8
8        9

# Tuple to Series and Dataframe

Tuple is collection of different datatype values

In [47]:
my_tuple = (1, 5, 3, 6, 2, 'a', 'c', 'b')
print(my_tuple)

# Convert my_tuple to a pandas Series
tuple_as_series = pd.Series(my_tuple)
print("\nTuple converted to Series:")
print(tuple_as_series)

(1, 5, 3, 6, 2, 'a', 'c', 'b')

Tuple converted to Series:
0    1
1    5
2    3
3    6
4    2
5    a
6    c
7    b
dtype: object

In [43]:
df_from_tuple = pd.DataFrame(my_tuple, columns=['Tuple_Elements'])
display(df_from_tuple)

  Tuple_Elements
0              1
1              5
2              3
3              6
4              2
5              a
6              c
7              b

In [44]:
# Filter rows where 'Tuple_Elements' is 'a'
filtered_df = df_from_tuple[df_from_tuple['Tuple_Elements'] == 'a']
display(filtered_df)

  Tuple_Elements
5              a

In [45]:
# Sort df_from_tuple by 'Tuple_Elements' column in ascending order
sorted_df = df_from_tuple.astype(str).sort_values(by='Tuple_Elements')
display(sorted_df)

  Tuple_Elements
0              1
4              2
2              3
1              5
3              6
5              a
7              b
6              c

In [41]:
# Add a new column named 'New_Column' to df_from_tuple
# The length of the list must match the number of rows in the DataFrame
new_column_values = [10, 20, 30, 40, 50, 60]
df_from_tuple['New_Column'] = new_column_values

display(df_from_tuple)

  Tuple_Elements  New_Column
0              1          10
1              2          20
2              3          30
3              a          40
4              b          50
5              c          60

In [46]:
tuple_series = df_from_tuple['Tuple_Elements']
display(tuple_series)

0    1
1    5
2    3
3    6
4    2
5    a
6    c
7    b
Name: Tuple_Elements, dtype: object

# Date and Time Date DataTypes in Pandas

In [50]:
from datetime import datetime, timedelta

print("--- Date and Time Date Types Practice ---")

# 1. Creating a Series of datetime objects
dates = pd.Series([
    datetime(2023, 1, 1),
    datetime(2023, 1, 15, 10, 30),
    datetime(2023, 2, 28, 23, 59, 59)
])
print("\n1. Series of datetime objects:")
display(dates)

# 2. Converting various data types to datetime
string_dates = pd.Series(['2024-03-01', '2024/03/02 14:00', 'March 3, 2024'])
converted_dates = pd.to_datetime(string_dates, format='mixed')
print("\n2. Converted string dates to datetime:")
display(converted_dates)

# 3. Accessing datetime properties
print("\n3. Accessing datetime properties (from converted_dates):")
print(f"Year: {converted_dates.dt.year.tolist()}")
print(f"Month: {converted_dates.dt.month.tolist()}")
print(f"Day: {converted_dates.dt.day.tolist()}")
print(f"Hour: {converted_dates.dt.hour.tolist()}")
print(f"Day of week (Monday=0): {converted_dates.dt.dayofweek.tolist()}")

# 4. Performing datetime arithmetic
future_dates = converted_dates + pd.Timedelta(days=7, hours=3)
print("\n4. Dates after adding 7 days and 3 hours:")
display(future_dates)

# 5. Calculating difference between dates
date_diff = future_dates - converted_dates
print("\n5. Difference between dates:")
display(date_diff)

--- Date and Time Date Types Practice ---

1. Series of datetime objects:

0   2023-01-01 00:00:00
1   2023-01-15 10:30:00
2   2023-02-28 23:59:59
dtype: datetime64[ns]

2. Converted string dates to datetime:

0   2024-03-01 00:00:00
1   2024-03-02 14:00:00
2   2024-03-03 00:00:00
dtype: datetime64[ns]

3. Accessing datetime properties (from converted_dates):
Year: [2024, 2024, 2024]
Month: [3, 3, 3]
Day: [1, 2, 3]
Hour: [0, 14, 0]
Day of week (Monday=0): [4, 5, 6]

4. Dates after adding 7 days and 3 hours:

0   2024-03-08 03:00:00
1   2024-03-09 17:00:00
2   2024-03-10 03:00:00
dtype: datetime64[ns]

5. Difference between dates:

0   7 days 03:00:00
1   7 days 03:00:00
2   7 days 03:00:00
dtype: timedelta64[ns]

In [51]:
# Create a sample DataFrame with datetime objects and values
df_time_data = pd.DataFrame({
    'Date': converted_dates,
    'Value': [100, 150, 200]
})
display(df_time_data)

                 Date  Value
0 2024-03-01 00:00:00    100
1 2024-03-02 14:00:00    150
2 2024-03-03 00:00:00    200

In [52]:
# Extract the month from the 'Date' column
df_time_data['Month'] = df_time_data['Date'].dt.month
print("\nDataFrame with Month column:")
display(df_time_data)

DataFrame with Month column:

                 Date  Value  Month
0 2024-03-01 00:00:00    100      3
1 2024-03-02 14:00:00    150      3
2 2024-03-03 00:00:00    200      3

In [54]:
# Group by month and aggregate (e.g., sum the 'Value' column)
monthly_agg = df_time_data.groupby('Month')['Value'].sum().reset_index()
print("\nAggregated data by Month:")
display(monthly_agg)

Aggregated data by Month:

   Month  Value
0      3    450

# Loc & iloc

In [58]:

# Re-defining car_data here to ensure it's available
cars = pd.Series(["BMW","Toyota","Honda","BYD","Mercedece"])
colors = pd.Series(["Black","White","Red","Blue","Merun"])
model = pd.Series([2000,2001,2002,2003,2004])
car_data = pd.DataFrame({"Car_type":cars,
                         "Color":colors,
                         "Model":model})

In [59]:
print("\n--- Practicing with .loc and .iloc ---\n")

# Display the original DataFrame for reference
print("Original car_data DataFrame:")
display(car_data)

--- Practicing with .loc and .iloc ---

Original car_data DataFrame:

    Car_type  Color  Model
0        BMW  Black   2000
1     Toyota  White   2001
2      Honda    Red   2002
3        BYD   Blue   2003
4  Mercedece  Merun   2004

In [65]:
print("\n--- Using .loc (label-based indexing) ---\n")

# 1. Select a single row by label
print("1. Select a single row (index label 0) using .loc:")
display(car_data.loc[0])

--- Using .loc (label-based indexing) ---

1. Select a single row (index label 0) using .loc:

Car_type      BMW
Color       Black
Model        2000
Name: 0, dtype: object

In [66]:
# 2. Select multiple rows by label
print("\n2. Select multiple rows (index labels 1 and 3) using .loc:")
display(car_data.loc[[1, 3]])

2. Select multiple rows (index labels 1 and 3) using .loc:

  Car_type  Color  Model
1   Toyota  White   2001
3      BYD   Blue   2003

In [67]:
# 3. Select rows and specific columns by label
print("\n3. Select rows (index labels 0 to 2) and 'Car_type', 'Color' columns using .loc:")
display(car_data.loc[0:2, ['Car_type', 'Color']])

3. Select rows (index labels 0 to 2) and 'Car_type', 'Color' columns using .loc:

  Car_type  Color
0      BMW  Black
1   Toyota  White
2    Honda    Red

In [68]:
# 4. Select rows based on a boolean condition
print("\n4. Select cars with 'Model' > 2002 using .loc (boolean indexing):")
display(car_data.loc[car_data['Model'] > 2002])

4. Select cars with 'Model' > 2002 using .loc (boolean indexing):

    Car_type  Color  Model
3        BYD   Blue   2003
4  Mercedece  Merun   2004

In [69]:
print("\n--- Using .iloc (integer-position-based indexing) ---\n")

# 1. Select a single row by integer position
print("1. Select a single row (position 0) using .iloc:")
display(car_data.iloc[0])

--- Using .iloc (integer-position-based indexing) ---

1. Select a single row (position 0) using .iloc:

Car_type      BMW
Color       Black
Model        2000
Name: 0, dtype: object

In [70]:
# 2. Select multiple rows by integer position
print("\n2. Select multiple rows (positions 1 and 3) using .iloc:")
display(car_data.iloc[[1, 3]])

2. Select multiple rows (positions 1 and 3) using .iloc:

  Car_type  Color  Model
1   Toyota  White   2001
3      BYD   Blue   2003

In [63]:
# 3. Select rows and specific columns by integer position
print("\n3. Select rows (positions 0 to 2) and columns (positions 0 and 1) using .iloc:")
display(car_data.iloc[0:3, 0:2]) # Note: iloc slicing is exclusive of the end index

3. Select rows (positions 0 to 2) and columns (positions 0 and 1) using .iloc:

  Car_type  Color
0      BMW  Black
1   Toyota  White
2    Honda    Red

In [11]:
# 4. Select all rows and a specific column by integer position
# Re-asserting car_data availability to prevent NameError
cars = pd.Series(["BMW","Toyota","Honda","BYD","Mercedece"])
colors = pd.Series(["Black","White","Red","Blue","Merun"])
model = pd.Series([2000,2001,2002,2003,2004])
car_data = pd.DataFrame({"Car_type":cars, "Color":colors, "Model":model})

print("\n4. Select all rows and 'Model' column (position 2) using .iloc:")
display(car_data.iloc[:, 2])

4. Select all rows and 'Model' column (position 2) using .iloc:

0    2000
1    2001
2    2002
3    2003
4    2004
Name: Model, dtype: int64

# Handle missing values during the pivot_kpis process

In [5]:
from __future__ import annotations

import re
from typing import Iterable, Optional

import numpy as np
import pandas as pd


_CURRENCY_RE = re.compile(r"[^0-9\-.]")


def strip_strings(df: pd.DataFrame, columns: Optional[Iterable[str]] = None) -> pd.DataFrame:
    """Strip whitespace from object/string columns (or provided columns).

    Returns a **copy**.
    """
    out = df.copy()

    if columns is None:
        # pandas string dtype or object dtype
        columns = [c for c in out.columns if out[c].dtype == "object" or str(out[c].dtype).startswith("string")]

    for c in columns:
        out[c] = out[c].astype("string").str.strip()

    return out


def normalize_case(
    df: pd.DataFrame,
    columns: Iterable[str],
    *,
    mode: str = "lower",
) -> pd.DataFrame:
    """Normalize string casing for selected columns.

    mode: "lower" | "upper" | "title"
    """
    out = df.copy()
    for c in columns:
        s = out[c].astype("string")
        if mode == "lower":
            out[c] = s.str.lower()
        elif mode == "upper":
            out[c] = s.str.upper()
        elif mode == "title":
            out[c] = s.str.title()
        else:
            raise ValueError("mode must be one of: lower, upper, title")
    return out


def to_datetime(df: pd.DataFrame, column: str, *, errors: str = "coerce") -> pd.DataFrame:
    """Convert a column to datetime. Returns a copy."""
    out = df.copy()
    out[column] = pd.to_datetime(out[column], errors=errors)
    return out


def currency_to_number(
    df: pd.DataFrame,
    column: str,
    *,
    errors: str = "coerce",
) -> pd.DataFrame:
    """Convert currency-like strings (e.g. "$4,000.00") to float.

    - Removes symbols/commas/spaces
    - Keeps minus sign and decimal

    Returns a copy.
    """
    out = df.copy()
    cleaned = out[column].astype("string").str.replace(_CURRENCY_RE, "", regex=True)
    out[column] = pd.to_numeric(cleaned, errors=errors)
    return out


def fillna_with_median(df: pd.DataFrame, columns: Iterable[str]) -> pd.DataFrame:
    """Fill NA in numeric columns with median. Returns a copy."""
    out = df.copy()
    for c in columns:
        out[c] = out[c].astype("float")
        out[c] = out[c].fillna(out[c].median())
    return out


def drop_duplicates_keep_last(df: pd.DataFrame, subset: Optional[list[str]] = None) -> pd.DataFrame:
    """Drop duplicates keeping last occurrence. Returns a copy."""
    return df.drop_duplicates(subset=subset, keep="last").copy()


def assert_no_duplicate_keys(df: pd.DataFrame, keys: list[str]) -> None:
    """Raise if keys are not unique (useful before a 1:1 merge).

    This is a common way to prevent inflated KPIs after joins.
    """
    dup = df.duplicated(subset=keys, keep=False)
    if bool(dup.any()):
        examples = df.loc[dup, keys].head(10)
        raise ValueError(f"Duplicate keys detected for {keys}. Examples:\n{examples}")

# --- Demonstration of Data Cleaning Utilities ---
print("\n--- Demonstration of Data Cleaning Utilities ---")

# Create a sample DataFrame
sample_data = pd.DataFrame({
    'Name': ['  Alice ', 'Bob   ', 'Charlie'],
    'Value': [' $1,000.00 ', '€500', '250.50'],
    'Status': ['active', 'PENDING ', 'inactive']
})
print("Original Sample DataFrame:")
display(sample_data)

# Demonstrate strip_strings
df_stripped = strip_strings(sample_data, columns=['Name', 'Status'])
print("\nAfter strip_strings:")
display(df_stripped)

# Demonstrate currency_to_number
df_currency_cleaned = currency_to_number(sample_data, column='Value')
print("\nAfter currency_to_number:")
display(df_currency_cleaned)

# Demonstrate normalize_case
df_normalized = normalize_case(sample_data, columns=['Status'], mode='upper')
print("\nAfter normalize_case (upper) on 'Status':")
display(df_normalized)

print("\nUtility functions defined and demonstrated successfully.")

--- Demonstration of Data Cleaning Utilities ---
Original Sample DataFrame:

       Name        Value    Status
0    Alice    $1,000.00     active
1    Bob            €500  PENDING
2   Charlie       250.50  inactive

After strip_strings:

      Name        Value    Status
0    Alice   $1,000.00     active
1      Bob         €500   PENDING
2  Charlie       250.50  inactive

After currency_to_number:

       Name   Value    Status
0    Alice   1000.0    active
1    Bob      500.0  PENDING
2   Charlie   250.5  inactive

After normalize_case (upper) on 'Status':

       Name        Value    Status
0    Alice    $1,000.00     ACTIVE
1    Bob            €500  PENDING
2   Charlie       250.50  INACTIVE

Utility functions defined and demonstrated successfully.

In [6]:
from __future__ import annotations

from pathlib import Path
from typing import Optional
import pandas as pd

def read_csv(
    path_or_url: str,
    *,
    na_values: Optional[list[str]] = None,
    dtype: Optional[dict[str, str]] = None,
) -> pd.DataFrame:
    """Reads a CSV file into a pandas DataFrame.

    Args:
        path_or_url: Local file path or a URL.
        na_values: Strings to treat as missing data (NaN).
        dtype: Dictionary to specify data types for columns.
    """
    # pd.read_csv is the standard pandas function for reading comma-separated values
    return pd.read_csv(path_or_url, na_values=na_values, dtype=dtype)

def read_excel(
    path: str | Path,
    *,
    sheet_name: str | int = 0,
    dtype: Optional[dict[str, str]] = None,
) -> pd.DataFrame:
    """Reads an Excel sheet into a pandas DataFrame.

    Args:
        path: Path to the .xlsx file.
        sheet_name: The name or index of the sheet (default is the first one).
    """
    return pd.read_excel(path, sheet_name=sheet_name, dtype=dtype)

def export_csv(df: pd.DataFrame, path: str | Path, *, index: bool = False) -> None:
    """Saves a DataFrame to a CSV file, creating directories if they don't exist.

    Logic:
    1. Convert the path string to a Path object for easier manipulation.
    2. Use .mkdir(parents=True) to create any missing folders in the path.
    3. Save the file using pandas .to_csv().
    """
    target_path = Path(path)
    # parents=True creates the directory 'data_exports' if it's missing
    # exist_ok=True prevents errors if the folder already exists
    target_path.parent.mkdir(parents=True, exist_ok=True)
    df.to_csv(target_path, index=index)

def export_excel(
    df: pd.DataFrame,
    path: str | Path,
    *,
    sheet_name: str = "data",
    index: bool = False,
) -> None:
    """Saves a DataFrame to an Excel file, creating parent directories.
    """
    target_path = Path(path)
    target_path.parent.mkdir(parents=True, exist_ok=True)
    df.to_excel(target_path, sheet_name=sheet_name, index=index)

# --- Reliability Check: Ensuring the code works as expected ---

# 1. Setup sample data locally within the cell for testing
cars = pd.Series(["BMW","Toyota","Honda","BYD","Mercedece"])
colors = pd.Series(["Black","White","Red","Blue","Merun"])
model = pd.Series([2000,2001,2002,2003,2004])
car_data = pd.DataFrame({"Car_type":cars, "Color":colors, "Model":model})

print("--- Testing I/O Utility Functions ---")

test_csv_path = "data_exports/car_data_test.csv"

# 2. Test Export: This proves the directory creation works
print(f"Step 1: Exporting data to {test_csv_path}...")
export_csv(car_data, test_csv_path)
print("Success: Directory checked/created and file saved.")

# 3. Test Import: This proves the 'round-trip' (save -> load) preserves data
print("\nStep 2: Reading the CSV back into 'loaded_df'...")
loaded_df = read_csv(test_csv_path)

# 4. Final Verification: Displaying results
print("\n--- Final Result: Loaded DataFrame ---")
display(loaded_df.head())

print("\nVerification Complete: The data loaded matches the data exported.")

--- Testing I/O Utility Functions ---
Step 1: Exporting data to data_exports/car_data_test.csv...
Success: Directory checked/created and file saved.

Step 2: Reading the CSV back into 'loaded_df'...

--- Final Result: Loaded DataFrame ---

    Car_type  Color  Model
0        BMW  Black   2000
1     Toyota  White   2001
2      Honda    Red   2002
3        BYD   Blue   2003
4  Mercedece  Merun   2004

Verification Complete: The data loaded matches the data exported.

# KPI utility

In [9]:
from __future__ import annotations

from dataclasses import dataclass
from typing import Iterable, Any
import pandas as pd

@dataclass(frozen=True)
class KpiSpec:
    """A structure to organize KPI metadata.

    date_col: The name of the column containing dates.
    dims: A list of categorical columns (dimensions) to group by.
    metrics: A mapping of {new_column_name: (source_column, aggregation_function)}.
    """
    date_col: str
    dims: list[str]
    metrics: dict[str, tuple[str, str]]

def add_month_column(df: pd.DataFrame, date_col: str, *, month_col: str = "month") -> pd.DataFrame:
    """Converts a date column to a string 'YYYY-MM' format for easy grouping."""
    out = df.copy()
    out[month_col] = pd.to_datetime(out[date_col], errors="coerce").dt.to_period("M").astype("string")
    return out

def kpi_groupby(
    df: pd.DataFrame,
    *,
    dims: Iterable[str],
    metrics: dict[str, tuple[str, str]],
) -> pd.DataFrame:
    """Groups data by dimensions and calculates multiple metrics at once."""
    agg_map = {out_name: (src, func) for out_name, (src, func) in metrics.items()}
    return df.groupby(list(dims), dropna=False).agg(**agg_map).reset_index()

def pivot_kpis(
    df_kpi: pd.DataFrame,
    *,
    index: list[str],
    columns: str,
    values: list[str],
    aggfunc: Any = "sum",
    fill_value: float | int | None = 0,
) -> pd.DataFrame:
    """Pivots 'Long' data into 'Wide' format.

    Added 'aggfunc' parameter to support different aggregations (sum, mean, etc.).
    """
    pt = df_kpi.pivot_table(index=index, columns=columns, values=values, aggfunc=aggfunc, fill_value=fill_value)
    pt.columns = ["__".join(map(str, col)).strip() for col in pt.columns.to_flat_index()]
    return pt.reset_index()

# --- Learning Demonstration: Updated with Custom Aggregation ---

raw_sales = pd.DataFrame({
    "sale_date": ["2023-01-05", "2023-01-15", "2023-02-10", "2023-02-20", "2023-01-20"],
    "region": ["North", "South", "North", "South", "North"],
    "revenue": [100, 200, 150, 300, 50],
    "order_id": [1, 2, 3, 4, 5]
})

sales_with_month = add_month_column(raw_sales, "sale_date")
kpi_summary = kpi_groupby(
    sales_with_month,
    dims=["month", "region"],
    metrics={"total_rev": ("revenue", "sum")}
)

# Demonstration: Using 'mean' instead of 'sum' for the pivot
report_mean = pivot_kpis(
    kpi_summary,
    index=["region"],
    columns="month",
    values=["total_rev"],
    aggfunc="mean"
)

print("Pivoted Report using 'mean' aggregation:")
display(report_mean)

Pivoted Report using 'mean' aggregation:

  region  total_rev__2023-01  total_rev__2023-02
0  North               150.0               150.0
1  South               200.0               300.0

In [10]:
print('--- Handling Missing Values in pivot_kpis ---\n')

# 1. Create data with a 'gap' (West region only exists in Feb)
sparse_data = pd.DataFrame({
    'month': ['2023-01', '2023-01', '2023-02', '2023-02'],
    'region': ['North', 'South', 'North', 'West'],
    'total_rev': [1000, 2000, 1500, 500]
})

print('Input Data (Note: West has no 2023-01 data):')
display(sparse_data)

# 2. Pivot with fill_value=0 (Default)
# This replaces missing combinations with 0
report_filled = pivot_kpis(
    sparse_data,
    index=['region'],
    columns='month',
    values=['total_rev'],
    fill_value=0
)

print('\nReport with fill_value=0 (Recommended for totals):')
display(report_filled)

# 3. Pivot with a custom fill_value (e.g., -1 or None)
report_custom = pivot_kpis(
    sparse_data,
    index=['region'],
    columns='month',
    values=['total_rev'],
    fill_value=-1
)

print('\nReport with fill_value=-1 (Useful to flag missing data):')
display(report_custom)

--- Handling Missing Values in pivot_kpis ---

Input Data (Note: West has no 2023-01 data):

     month region  total_rev
0  2023-01  North       1000
1  2023-01  South       2000
2  2023-02  North       1500
3  2023-02   West        500

Report with fill_value=0 (Recommended for totals):

  region  total_rev__2023-01  total_rev__2023-02
0  North                1000                1500
1  South                2000                   0
2   West                   0                 500

Report with fill_value=-1 (Useful to flag missing data):

  region  total_rev__2023-01  total_rev__2023-02
0  North                1000                1500
1  South                2000                  -1
2   West                  -1                 500