<a href="https://colab.research.google.com/github/omarfarukcse/Machine-learning/blob/Pandas/Pandas_Practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import pandas as pd

print(f"Pandas Version check : {pd.__version__}")

Pandas Version check : 2.2.2

In [8]:
#Creating A Series
cars = pd.Series(["BMW","Toyota","Honda","BYD","Mercedece"])
print(cars)

0          BMW
1       Toyota
2        Honda
3          BYD
4    Mercedece
dtype: object

In [10]:
colors = pd.Series(["Black","White","Red","Blue","Merun"])
colors

0    Black
1    White
2      Red
3     Blue
4    Merun
dtype: object

In [13]:
model = pd.Series([2000,2001,2002,2003,2004])
model

0    2000
1    2001
2    2002
3    2003
4    2004
dtype: int64

In [14]:
car_data = pd.DataFrame({"Car_type":cars,
                         "Color":colors,
                         "Model":model})
car_data

    Car_type  Color  Model
0        BMW  Black   2000
1     Toyota  White   2001
2      Honda    Red   2002
3        BYD   Blue   2003
4  Mercedece  Merun   2004

In [15]:
from google.colab import sheets
sheet = sheets.InteractiveSheet(df=car_data)

https://docs.google.com/spreadsheets/d/1yUNaK6sSz5efQDwsxQEdI8BDnp6FUSecj1Ua5DdA28o/edit#gid=0