<a href="https://colab.research.google.com/github/omarfarukcse/Machine-learning/blob/Pandas/Pandas_Practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

print(f"Pandas Version check : {pd.__version__}")

Pandas Version check : 2.2.2

In [ ]:
#Creating A Series
cars = pd.Series(["BMW","Toyota","Honda","BYD","Mercedece"])
print(cars)

0          BMW
1       Toyota
2        Honda
3          BYD
4    Mercedece
dtype: object

In [ ]:
colors = pd.Series(["Black","White","Red","Blue","Merun"])
colors

0    Black
1    White
2      Red
3     Blue
4    Merun
dtype: object

In [ ]:
model = pd.Series([2000,2001,2002,2003,2004])
model

0    2000
1    2001
2    2002
3    2003
4    2004
dtype: int64

In [ ]:
car_data = pd.DataFrame({"Car_type":cars,
                         "Color":colors,
                         "Model":model})
car_data

    Car_type  Color  Model
0        BMW  Black   2000
1     Toyota  White   2001
2      Honda    Red   2002
3        BYD   Blue   2003
4  Mercedece  Merun   2004

In [ ]:
from google.colab import sheets
sheet = sheets.InteractiveSheet(df=car_data)

https://docs.google.com/spreadsheets/d/1yUNaK6sSz5efQDwsxQEdI8BDnp6FUSecj1Ua5DdA28o/edit#gid=0

### Dictionary to Series and DataFrame

In [3]:
#Making Dictionary
data ={
    'name':["Omar","Efaz","Kobir","Jobair"],
    'age' : [24,23,24,25],
    'city':["Rangpur","Bogura","Tangail","Barishal"]
}
data

{'name': ['Omar', 'Efaz', 'Kobir', 'Jobair'],
 'age': [24, 23, 24, 25],
 'city': ['Rangpur', 'Bogura', 'Tangail', 'Barishal']}

In [20]:
#Making Series
print(f"This is a Name series :\n{pd.Series(data['name'], name='Name')}")
print(f"This is a Age series :\n{pd.Series(data['age'], name='Age')}")
print(f"This is a City series :\n{pd.Series(data['city'], name='City')}")

# naming the series also coded. name = 'Name' -> this is that
# also we can make variables s_name,s_age,s_city than print

This is a Name series :
0      Omar
1      Efaz
2     Kobir
3    Jobair
Name: Name, dtype: object
This is a Age series :
0    24
1    23
2    24
3    25
Name: Age, dtype: int64
This is a City series :
0     Rangpur
1      Bogura
2     Tangail
3    Barishal
Name: City, dtype: object

In [17]:
#Making DataFrame
pd.DataFrame(data)

     name  age      city
0    Omar   24   Rangpur
1    Efaz   23    Bogura
2   Kobir   24   Tangail
3  Jobair   25  Barishal

In [21]:
#Another way
pd.DataFrame.from_dict(data)

     name  age      city
0    Omar   24   Rangpur
1    Efaz   23    Bogura
2   Kobir   24   Tangail
3  Jobair   25  Barishal

#Set to Series and DataFrame

In [23]:
#Set create with {} -> this

s ={1,2,3,4,5,6,7,8,9}
s

{1, 2, 3, 4, 5, 6, 7, 8, 9}

In [24]:
type(s)

set

In [32]:
#we must have to convert set to list or tuple.
#Otherwise It will not work
print(f"Convert in List then Series : \n{pd.Series(list(s))}")
print(f"Convert in Tuple then Series : \n{pd.Series(tuple(s))}")

Convert in List then Series :
0    1
1    2
2    3
3    4
4    5
5    6
6    7
7    8
8    9
dtype: int64
Convert in Tuple then Series :
0    1
1    2
2    3
3    4
4    5
5    6
6    7
7    8
8    9
dtype: int64

In [38]:
#Set to DataFrame ... Easy Task heheheheh
pd.DataFrame(s, columns=["set_val"])

   set_val
0        1
1        2
2        3
3        4
4        5
5        6
6        7
7        8
8        9

# Tuple to Series and Dataframe

Tuple is collection of different datatype values

In [47]:
my_tuple = (1, 5, 3, 6, 2, 'a', 'c', 'b')
print(my_tuple)

# Convert my_tuple to a pandas Series
tuple_as_series = pd.Series(my_tuple)
print("\nTuple converted to Series:")
print(tuple_as_series)

(1, 5, 3, 6, 2, 'a', 'c', 'b')

Tuple converted to Series:
0    1
1    5
2    3
3    6
4    2
5    a
6    c
7    b
dtype: object

In [43]:
df_from_tuple = pd.DataFrame(my_tuple, columns=['Tuple_Elements'])
display(df_from_tuple)

  Tuple_Elements
0              1
1              5
2              3
3              6
4              2
5              a
6              c
7              b

In [44]:
# Filter rows where 'Tuple_Elements' is 'a'
filtered_df = df_from_tuple[df_from_tuple['Tuple_Elements'] == 'a']
display(filtered_df)

  Tuple_Elements
5              a

In [45]:
# Sort df_from_tuple by 'Tuple_Elements' column in ascending order
sorted_df = df_from_tuple.astype(str).sort_values(by='Tuple_Elements')
display(sorted_df)

  Tuple_Elements
0              1
4              2
2              3
1              5
3              6
5              a
7              b
6              c

In [41]:
# Add a new column named 'New_Column' to df_from_tuple
# The length of the list must match the number of rows in the DataFrame
new_column_values = [10, 20, 30, 40, 50, 60]
df_from_tuple['New_Column'] = new_column_values

display(df_from_tuple)

  Tuple_Elements  New_Column
0              1          10
1              2          20
2              3          30
3              a          40
4              b          50
5              c          60

In [46]:
tuple_series = df_from_tuple['Tuple_Elements']
display(tuple_series)

0    1
1    5
2    3
3    6
4    2
5    a
6    c
7    b
Name: Tuple_Elements, dtype: object

# Date and Time Date DataTypes in Pandas

In [50]:
from datetime import datetime, timedelta

print("--- Date and Time Date Types Practice ---")

# 1. Creating a Series of datetime objects
dates = pd.Series([
    datetime(2023, 1, 1),
    datetime(2023, 1, 15, 10, 30),
    datetime(2023, 2, 28, 23, 59, 59)
])
print("\n1. Series of datetime objects:")
display(dates)

# 2. Converting various data types to datetime
string_dates = pd.Series(['2024-03-01', '2024/03/02 14:00', 'March 3, 2024'])
converted_dates = pd.to_datetime(string_dates, format='mixed')
print("\n2. Converted string dates to datetime:")
display(converted_dates)

# 3. Accessing datetime properties
print("\n3. Accessing datetime properties (from converted_dates):")
print(f"Year: {converted_dates.dt.year.tolist()}")
print(f"Month: {converted_dates.dt.month.tolist()}")
print(f"Day: {converted_dates.dt.day.tolist()}")
print(f"Hour: {converted_dates.dt.hour.tolist()}")
print(f"Day of week (Monday=0): {converted_dates.dt.dayofweek.tolist()}")

# 4. Performing datetime arithmetic
future_dates = converted_dates + pd.Timedelta(days=7, hours=3)
print("\n4. Dates after adding 7 days and 3 hours:")
display(future_dates)

# 5. Calculating difference between dates
date_diff = future_dates - converted_dates
print("\n5. Difference between dates:")
display(date_diff)

--- Date and Time Date Types Practice ---

1. Series of datetime objects:

0   2023-01-01 00:00:00
1   2023-01-15 10:30:00
2   2023-02-28 23:59:59
dtype: datetime64[ns]

2. Converted string dates to datetime:

0   2024-03-01 00:00:00
1   2024-03-02 14:00:00
2   2024-03-03 00:00:00
dtype: datetime64[ns]

3. Accessing datetime properties (from converted_dates):
Year: [2024, 2024, 2024]
Month: [3, 3, 3]
Day: [1, 2, 3]
Hour: [0, 14, 0]
Day of week (Monday=0): [4, 5, 6]

4. Dates after adding 7 days and 3 hours:

0   2024-03-08 03:00:00
1   2024-03-09 17:00:00
2   2024-03-10 03:00:00
dtype: datetime64[ns]

5. Difference between dates:

0   7 days 03:00:00
1   7 days 03:00:00
2   7 days 03:00:00
dtype: timedelta64[ns]

In [51]:
# Create a sample DataFrame with datetime objects and values
df_time_data = pd.DataFrame({
    'Date': converted_dates,
    'Value': [100, 150, 200]
})
display(df_time_data)

                 Date  Value
0 2024-03-01 00:00:00    100
1 2024-03-02 14:00:00    150
2 2024-03-03 00:00:00    200

In [52]:
# Extract the month from the 'Date' column
df_time_data['Month'] = df_time_data['Date'].dt.month
print("\nDataFrame with Month column:")
display(df_time_data)

DataFrame with Month column:

                 Date  Value  Month
0 2024-03-01 00:00:00    100      3
1 2024-03-02 14:00:00    150      3
2 2024-03-03 00:00:00    200      3

In [54]:
# Group by month and aggregate (e.g., sum the 'Value' column)
monthly_agg = df_time_data.groupby('Month')['Value'].sum().reset_index()
print("\nAggregated data by Month:")
display(monthly_agg)

Aggregated data by Month:

   Month  Value
0      3    450

# Loc & iloc

In [58]:

# Re-defining car_data here to ensure it's available
cars = pd.Series(["BMW","Toyota","Honda","BYD","Mercedece"])
colors = pd.Series(["Black","White","Red","Blue","Merun"])
model = pd.Series([2000,2001,2002,2003,2004])
car_data = pd.DataFrame({"Car_type":cars,
                         "Color":colors,
                         "Model":model})

In [59]:
print("\n--- Practicing with .loc and .iloc ---\n")

# Display the original DataFrame for reference
print("Original car_data DataFrame:")
display(car_data)

--- Practicing with .loc and .iloc ---

Original car_data DataFrame:

    Car_type  Color  Model
0        BMW  Black   2000
1     Toyota  White   2001
2      Honda    Red   2002
3        BYD   Blue   2003
4  Mercedece  Merun   2004

In [60]:
print("\n--- Using .loc (label-based indexing) ---\n")

# 1. Select a single row by label
print("1. Select a single row (index label 0) using .loc:")
display(car_data.loc[0])

# 2. Select multiple rows by label
print("\n2. Select multiple rows (index labels 1 and 3) using .loc:")
display(car_data.loc[[1, 3]])

# 3. Select rows and specific columns by label
print("\n3. Select rows (index labels 0 to 2) and 'Car_type', 'Color' columns using .loc:")
display(car_data.loc[0:2, ['Car_type', 'Color']])

# 4. Select rows based on a boolean condition
print("\n4. Select cars with 'Model' > 2002 using .loc (boolean indexing):")
display(car_data.loc[car_data['Model'] > 2002])

--- Using .loc (label-based indexing) ---

1. Select a single row (index label 0) using .loc:

Car_type      BMW
Color       Black
Model        2000
Name: 0, dtype: object

2. Select multiple rows (index labels 1 and 3) using .loc:

  Car_type  Color  Model
1   Toyota  White   2001
3      BYD   Blue   2003

3. Select rows (index labels 0 to 2) and 'Car_type', 'Color' columns using .loc:

  Car_type  Color
0      BMW  Black
1   Toyota  White
2    Honda    Red

4. Select cars with 'Model' > 2002 using .loc (boolean indexing):

    Car_type  Color  Model
3        BYD   Blue   2003
4  Mercedece  Merun   2004

In [61]:
print("\n--- Using .iloc (integer-position-based indexing) ---\n")

# 1. Select a single row by integer position
print("1. Select a single row (position 0) using .iloc:")
display(car_data.iloc[0])

# 2. Select multiple rows by integer position
print("\n2. Select multiple rows (positions 1 and 3) using .iloc:")
display(car_data.iloc[[1, 3]])

# 3. Select rows and specific columns by integer position
print("\n3. Select rows (positions 0 to 2) and columns (positions 0 and 1) using .iloc:")
display(car_data.iloc[0:3, 0:2]) # Note: iloc slicing is exclusive of the end index

# 4. Select all rows and a specific column by integer position
print("\n4. Select all rows and 'Model' column (position 2) using .iloc:")
display(car_data.iloc[:, 2])

--- Using .iloc (integer-position-based indexing) ---

1. Select a single row (position 0) using .iloc:

Car_type      BMW
Color       Black
Model        2000
Name: 0, dtype: object

2. Select multiple rows (positions 1 and 3) using .iloc:

  Car_type  Color  Model
1   Toyota  White   2001
3      BYD   Blue   2003

3. Select rows (positions 0 to 2) and columns (positions 0 and 1) using .iloc:

  Car_type  Color
0      BMW  Black
1   Toyota  White
2    Honda    Red

4. Select all rows and 'Model' column (position 2) using .iloc:

0    2000
1    2001
2    2002
3    2003
4    2004
Name: Model, dtype: int64